import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from '../components/Nav'
import {Box, Center,Flex, Container} from "@chakra-ui/react"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Video Call</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Nav/>
        <Container h="80vh"><Flex h="100%" direction="row" justify="center" align="center" ><h1>Hello</h1></Flex></Container>
    </div>
  );
};

export default Home;
